### ISSUE TITLE
Load data from xwing-data using manage.py command

### ISSUE THREAD

**Issue by OskarBreach** [OskarBreach/hit-hit-crit#1]
Replace the migration 0002_load_data with a manage.py command, which can be re-run independently of the migrations.

[Writing custom django-admin commands](https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/).

**Comment by Tarnal12** [comment]
Done. The old migration has been removed, and a new command added (xwingdata/management/commands/populatedata.py)

Runs basically the same code as before but can be done independently of migrations.

**Comment by OskarBreach** [comment]
Fixed by commit https://github.com/OskarBreach/hit-hit-crit/commit/49e0099d73dbbe71fe0b4a7631c2a90aa59a226b
